### ISSUE TITLE
Riddl validates with empty {}

### ISSUE THREAD

**Issue by JamesYopp** [ossuminc/riddl#479]
for example, when specifying the KSO application the following was provided in a page definition:

`page SigninPage {}`

It should have been written as:

`page SigninPage {???}`

**Comment by reid-spencer** [comment]
This can't be replicated with the most recent version of riddl. You'll get a message like:
```riddl
Expected one of ("}" | "include" | "constant" | "command" | "event" | "query" | "result" | "record" | "type" | "term" | "outlet" | "inlet" | "function" | "handler" | "option" | "options" | "???")
```
