### ISSUE TITLE
[FEATURE] Add Timing Data to Parsing Results

### ISSUE THREAD

**Issue by AlexWeinstein92** [ossuminc/riddl#664]
### **Is your feature already requested in another issue?**
No

### **Is your feature a defect?**
No

### **Is your feature request related to a problem? Please describe.**
How to display timing results to users in the IDEA plugin

### **Describe the solution you'd like**
Timing results should be either packed into `PassesResult` or else returned along with it as a tuple or other structure

**Comment by reid-spencer** [comment]
> How to display timing results to users in the IDEA plugin

I think the correct way to show timing data is the same way it is done in riddlc: in the logged output.  That is the IDEA plugin's textual output log should contain the timing data exactly the way riddlc would have logged it. Thus, it isn't necessary to change 100 apis to include timing data. 

###

**Comment by reid-spencer** [comment]
@AlexWeinstein92 - Do you concur with the above analysis? Just use the Logger? If so, please close this Issue.

**Comment by reid-spencer** [comment]
Insufficient responses. Closing this in favor of only putting out timing in the Logger.
