### ISSUE TITLE
[FEATURE] Export keywords, readability, punctuation as `Seq[String]`s

### ISSUE THREAD

**Issue by AlexWeinstein92** [ossuminc/riddl#675]
### **Is your feature already requested in another issue?**
No

### **Is your feature a defect?**
From the perspective of riddl-idea-plugin, yes

### **Is your feature request related to a problem? Please describe.**
Manual updating of keywords in plugin

### **Describe the solution you'd like**
A `def` on each of `com.ossuminc.riddl.language.parsing.{Keyword, Readibility, Punctuation} that returns all its `val`s in a `Seq`

`Readability.ByAs` need not be included in the `Seq[String]`s, as it is already defined individually for `by` and `as`

### **Describe the alternatives you've considered**
None

**Comment by reid-spencer** [comment]
This is perhaps optimizing for a rare event, now.  The last slew of changes are likely the final ones for 1.0 release so no more keyword changes are expected for a while.  I will consider this for downstream consumers when additional language changes become necessary.

**Comment by reid-spencer** [comment]
Implemented.
