### ISSUE TITLE
[DEFECT] noAnsiMessages has no effect programmatically, is not recognized in command line

### ISSUE THREAD

**Issue by AlexWeinstein92** [ossuminc/riddl#677]
### **Symptom**
In console:
![image](https://github.com/user-attachments/assets/c26cf951-d1f1-45f1-b74e-a8bc242cc508)

In plugin:
No matter the value of `CommonOptions.noANSIMessages`, ANSI codes are kept in output

### **Expected Behavior**
ANSI colouring is turned off when the settings is `true`

### **Steps To Reproduce**
See symptoms section

### **Output From `riddlc info`**
 ```[info] About riddlc:
[info]            name: riddlc
[info]         version: 0.53.1
[info]   documentation: https://riddl.tech
[info]       copyright: © 2019-2024 Ossum, Inc.
[info]        built at: 2024-10-18 12:48:09.409-0400
[info]        licenses: Apache-2.0
[info]    organization: Ossum, Inc.
[info]   scala version: 3.4.3
[info]     sbt version: 1.10.2
[info]        jvm name: OpenJDK 64-Bit Server VM
[info]     jvm version: 23+37-2369
[info]   operating sys: Mac OS X```

**Comment by reid-spencer** [comment]
@AlexWeinstein92 👍 
The option to use is --noANSIMessages, not --no-ansi-messages.  Can you confirm that the former option works, please?

**Comment by reid-spencer** [comment]
And, yes, it should accept --no-ansi-messages

**Comment by reid-spencer** [comment]
This is waiting on a pending change that will consolidate CommonOptions into "PlatformContext" as a given/using context.
