### ISSUE TITLE
[FEATURE] Return all RPIs

### ISSUE THREAD

**Issue by AlexWeinstein92** [ossuminc/riddl#682]
### **Is your feature already requested in another issue?**
No

### **Is your feature a defect?**
No

### **Is your feature request related to a problem? Please describe.**
The plugin needs to find out whether the edited file is configured to compile so it can find out whether the edit deserves a squiggly line

### **Describe the solution you'd like**
A way to generate only the RPIs, or otherwise having them available after parsing fails

### **Describe the alternatives you've considered**
N/A

**Comment by reid-spencer** [comment]
@AlexWeinstein92 - would it be okay if it returned a `Seq[java.nio.file.Path]` instead of heavyweight RPI? I think you just want the file paths, right?

**Comment by reid-spencer** [comment]
Resolved by providing the `getURLs`  and `parseRootWithURLs` methods in TopLevelParser.
