### ISSUE TITLE
[DEFECT] `TopLevelParser.parseRootWithURLs` always returns an empty list of URLs on failure

### ISSUE THREAD

**Issue by AlexWeinstein92** [ossuminc/riddl#689]
### **Symptom**
The test for failure of `parseRootWithURLs` expects an empty `Seq`; the URLs on failure are essential to an ongoing task in the plugin

### **Expected Behavior**
When `parseRootWithURLs` return `Left`, the `URL`s element in the tuples should be populated
Ideally the `URL`s and the `Message.At`s would be grouped together so they can be referenced against each other more accurately

### **Steps To Reproduce**
Option 1: Run test `return URLs on failure` in `TopLevelParserTest`
Option 2: Write a java script using `TopLevelParser` and make it fail with error messages

**Comment by reid-spencer** [comment]
The behavior of that function is to not return the RPI's top level thing because it could be a string and because the programmer already knows about it. It only returns the URLs of the include statements. If your parse has no includes, you'll get an empty list.

**Comment by AlexWeinstein92** [comment]
Just needed a `clean`
